setup:
    output_path: output/
    trainModel: true
dataset:
    name: DTUDataset
    folder: ${DATASET}/FuglsangAAD/eeg_new/
    stimuli_path: ${DATASET}/FuglsangAAD/stimuli
    pre_processed: null
    raw: [S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12, S13, S14, S15, S16, S17, S18]
    all_sbjs: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
    from_sbj: 0
    to_sbj: 18
    scaler:
        type: RobustScaler
        feature_range: [-1,1]
        path: null
    channels: ['Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2']    # Fuglsang 64    
    windows: [1, 2, 5, 10, 20, 40]   

    eeg_context: 0.4
    preprocess: ThorntonM
    splits: [0.8, 0.2, 0]
    training_window: 0.4 # seconds
    step: 0 #seconds
    sr: 125
    duplicate: false # true/false
    n_streams: 2

model:
    tag: EEGNetAAD
    model_name: EEGNetAAD
    pretrained: ./output/EEGNetAAD_DTUDataset/EEGNetAAD_SI
    # pretrained: null
    context: 0.4
    F1: 8
    D: 2
    F2: 16
    dropout: 0.12
        
learning:
    nFold: 8
    nRep: 1
    threshold: 0.5
    loss_function:
        type: correlation
        name: CorrelationLoss
    optimizer:
        opt: NAdam
        lr: 1e-4
        lr_decay_step: 100
        lr_decay_gamma: 0.1
        eps: 0.00000001
        weight_decay: 1e-6
        momentum: 0
        betas: (0.9, 0.999)
    running:
        num_workers: 2
        batch_size: 128
        epochs: 50
        lambda: 100.0
        print_every: 1
        early_stop: loss
        parallelization: multi-fold
        device: [0, 1, 2, 3]
        save_path: EEGNetAAD.pth
