#initial settings
setup:
    output_path: output/
    trainModel: false
dataset:    
    name: EventAADDataset
    folder: ${DATASET}/EventAAD/raw #${DATASET}/EventAAD/raw # D:\OneDrive\WORK\data\BIDS\eventaad
    stimuli_path: ${DATASET}/EventAAD/raw/stimuli/real_story_snippet
    pre_processed: null
    raw: ['001', '002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012', '014', '015', '016', '017', '018', '019', '020', '021', '022', '023', '024', '025']
    all_sbjs: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
    from_sbj: 0
    to_sbj: 24
    scaler:
        type: RobustScaler
        feature_range: [-1,1]
        path: null
    channels: ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FC5', 'FC1', 'FC2', 'FC6', 'M1', 'T7-T3', 'C3', 'Cz', 'C4', 'T8-T4', 'M2', 'CP5', 'CP1', 'CP2', 'CP6', 'P7-T5', 'P3', 'Pz', 'P4', 'P8-T6', 'POz', 'O1', 'Oz', 'O2']
    windows: [1, 2, 5, 10, 20]    
    
    eeg_context: 0.4    
    preprocess: proposed # ThorntonM/proposed/null
    splits: [0.8, 0.2, 0]
    training_window: 10 # seconds
    step: 0.5 #seconds
    sr: 64
    n_streams: 2

model:
    model_name: AADNet
    pretrained: output/AADNet_EventAADDataset/AADNet_SI
    feature_freeze: false
    
    in_channels: 32 # 32 for eventaad, 64 for fuglsang and das2019
    chns_1: [32, [16, 8], [8, 8], [4, 8], [2, 8], 8]
    kernels_1: [1, 19, 25, 33, 39, 3]   
    chns_1_aud: [1, [1, 4], [1, 4], 0]
    kernels_1_aud: [1, 65, 81, 3]
    act_1: relu
    pool_stride_1: 2 
    hidden_size: 0
    dropout: 0.4     
        
learning:
    nFold: 8
    nRep: 1
    threshold: 0.5
    loss_function:
        type: correlation
        name: CrossEntropyLoss
    optimizer:
        opt: AdamW
        lr: 0.00005
        lr_decay_step: 10
        lr_decay_gamma: 0.2
        eps: 0.00000001
        weight_decay: 0.01
        momentum: 0
        betas: (0.9, 0.999)
    running:
        num_workers: 0
        batch_size: 32
        epochs: 20
        lambda: 100.0
        print_every: 1
        early_stop: loss
        parallelization: multi-fold
        device: [0, 1, 2, 3]
        save_path: AADNet.pth
