#initial settings
setup:
    output_path: output/
    trainModel: false
dataset:   
    name: DTUDataset
    folder: ${DATASET}/FuglsangAAD/eeg_new/
    stimuli_path: ${DATASET}/FuglsangAAD/stimuli
    pre_processed: null
    raw: [S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12, S13, S14, S15, S16, S17, S18]
    all_sbjs: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
    from_sbj: 0
    to_sbj: 18
    scaler:
        type: RobustScaler
        feature_range: [-1,1]
        path: null
    channels: ['Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2']    # Fuglsang 64    
    LChO_groups: [['AF7', 'AF3','F3', 'F5', 'F7'], ['Fp1','Fpz','Fp2','AFz','F1','Fz','F2'], ['AF8', 'AF4','F4', 'F6', 'F8'], ['FT7', 'FC5', 'FC3','T7','C5','C3','TP7', 'CP5', 'CP3'], ['FC1','FCz','FC2','C1','Cz','C2','CP1','CPz','CP2'], ['FT8', 'FC6', 'FC4','T8','C6','C4','TP8', 'CP6', 'CP4'], ['P9','P7','P5','P3','PO3','PO7'],['P1','P2','Pz','POz','O1','Oz','O2','Iz'],['P10','P8','P6','P4','PO4','PO8']]
    windows: [1, 2, 5, 10, 20, 40]       
    
    eeg_context: 0.4    
    preprocess: proposed # ThorntonM/proposed/null
    splits: [0.8, 0.2, 0]
    training_window: 10 # seconds
    step: 0.5 #seconds
    sr: 64
    n_streams: 2

model:
    model_name: AADNet
    pretrained: output/AADNet_DTUDataset/AADNet_SI
    feature_freeze: false
    
    in_channels: 64 # 32 for eventaad, 64 for fuglsang and das2019
    chns_1: [32, [16, 8], [8, 8], [4, 8], [2, 8], 8]
    kernels_1: [1, 19, 25, 33, 39, 3]   
    chns_1_aud: [1, [1, 4], [1, 4], 0]
    kernels_1_aud: [1, 65, 81, 3]
    act_1: relu
    pool_stride_1: 2 
    hidden_size: 0
    dropout: 0.4     
        
learning:
    nFold: 8
    nRep: 1
    threshold: 0.5
    loss_function:
        type: correlation
        name: CrossEntropyLoss
    optimizer:
        opt: AdamW
        lr: 0.00005
        lr_decay_step: 10
        lr_decay_gamma: 0.2
        eps: 0.00000001
        weight_decay: 0.01
        momentum: 0
        betas: (0.9, 0.999)
    running:
        num_workers: 0
        batch_size: 32
        epochs: 20
        lambda: 100.0
        print_every: 1
        early_stop: loss
        parallelization: multi-fold
        device: [0, 1, 2, 3]
        save_path: AADNet.pth
